{
 "title": "BackStage LogAnalytics Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Health ratio",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"backstage\"}[1h]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(count_over_time({container=\"backstage\"} |~ \"(Error|FATAL)\" [1h]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Log Level Chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"backstage\"} |=`\\\"level\\\":\\\"info\\\"` [1h]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(count_over_time({container=\"backstage\"} |=`\\\"level\\\":\\\"warn\\\"` [1h]))",
     "legendFormat": "Warn"
    },
    {
     "expr": "sum(count_over_time({container=\"backstage\"} |=`\\\"level\\\":\\\"error\\\"` [1h]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "All errors timechart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({container=\"backstage\"} |~ \"(Error|FATAL)\" [30s])"
    }
   ]
  },
  {
   "title": "All Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"backstage\"}"
    }
   ]
  },
  {
   "title": "Error Log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"backstage\"} |~ \"(Error|FATAL)\""
    }
   ]
  }
 ]
}