promtail:
  create-namespace: true
  config:
    clients:
      - url: http://loki-gateway/loki/api/v1/push
    scrape_configs:
      - job_name: pod-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/*log
    pipeline_stages:
      - replace:
          expression: "\\\\"
          replace: ""
